// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package commands

import (
	"example/internal/app/service"
	"example/internal/infrastructure/repos/mysqlreposimpl"
	"example/internal/infrastructure/repos/redisrepoimpl"
	"example/internal/pkg/db"
	"example/internal/pkg/logger"
)

// Injectors from wire.go:

// NewAccountCommand 实例化账号管理命令
func NewAccountCommand(dc *db.Connector, rdb *db.Redis, lg *logger.Logger) *AccountHandler {
	accountRepository := mysqlreposimpl.NewAccountRepository(dc, rdb, lg)
	accountService := service.NewAccountService(accountRepository)
	accountHandler := NewAccountHandler(accountService, lg)
	return accountHandler
}

// NewUserCommand 实例化账号管理命令
func NewUserCommand(dc *db.Connector, rdb *db.Redis, lg *logger.Logger) *UserHandler {
	sessionRepository := redisrepoimpl.NewSessionRepository(rdb)
	sessionService := service.NewSessionService(sessionRepository)
	userHandler := NewUserHandler(sessionService)
	return userHandler
}
