// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package commands

import (
	"example/internal/app/service"
	"example/internal/infrastructure/depend"
	"example/internal/infrastructure/repos/mysqlreposimpl"
	"example/internal/infrastructure/repos/redisrepoimpl"
)

// Injectors from wire.go:

// NewAccountCommand 实例化账号管理命令
func NewAccountCommand(inject *depend.Injecter) *AccountHandler {
	accountRepository := mysqlreposimpl.NewAccountRepository(inject)
	accountService := service.NewAccountService(accountRepository)
	accountHandler := NewAccountHandler(accountService, inject)
	return accountHandler
}

// NewUserCommand 实例化账号管理命令
func NewUserCommand(inject *depend.Injecter) *UserHandler {
	sessionRepository := redisrepoimpl.NewSessionRepository(inject)
	sessionService := service.NewSessionService(sessionRepository)
	userHandler := NewUserHandler(sessionService)
	return userHandler
}
