// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package controller

import (
	"demo/internal/app/controller/handlers"
	"demo/internal/app/services"
	"demo/internal/domain"
	"demo/internal/infrastructure/repos"
	"github.com/jmoiron/sqlx"
	"github.com/redis/go-redis/v9"
)

// Injectors from wire.go:

// NewUserAPI 实例化用户控制器
func NewUserAPI(db *sqlx.DB, rdb *redis.Client) domain.UserHandler {
	userRepository := repos.NewUserRepository(db, rdb)
	userService := services.NewUserService(userRepository)
	userHandler := handlers.NewUserHandler(userService)
	return userHandler
}
