# API服务配置
server:
  addr: :8080       # HTTP绑定端口
  log: info         # 日志等级：trance, debug, info, warn, error, fatal, panic

# MySQL配置
mysql:
  host: mysql:3306
  user: root
  password: mysql_pwd
  database: demo
  debug: false
  maxIdleConn: 10
  maxOpenConn: 100
  connMaxIdleTime: 1h
  connMaxLifetime: 1h

# redis 配置
redis:
  host: redis:6379
  password:
  database: 0
