// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package handlers

import (
	"demo/internal/app/service"
	"demo/internal/infrastructure/repos/mysql_repos_impl"
	"demo/internal/infrastructure/repos/redis_repos_impl"
	"demo/internal/pkg/db"
	"github.com/redis/go-redis/v9"
)

// Injectors from wire.go:

// NewUserAPI 实例化用户控制器
func NewUserAPI(dc *db.Connector, rdb *redis.Client) *UserHandler {
	userRepository := mysql_repos_impl.NewUserRepository(dc, rdb)
	userService := service.NewUserService(userRepository)
	sessionRepository := redis_repos_impl.NewSessionRepository(rdb)
	sessionService := service.NewSessionService(sessionRepository)
	userHandler := NewUserHandler(userService, sessionService)
	return userHandler
}

// NewAccountAPI 实例化管理员账户控制器
func NewAccountAPI(dc *db.Connector, rdb *redis.Client) *AccountHandler {
	accountRepository := mysql_repos_impl.NewAccountRepository(dc, rdb)
	accountService := service.NewAccountService(accountRepository)
	sessionRepository := redis_repos_impl.NewSessionRepository(rdb)
	sessionService := service.NewSessionService(sessionRepository)
	accountHandler := NewAccountHandler(accountService, sessionService)
	return accountHandler
}
