// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package handlers

import (
	"example/internal/app/service"
	"example/internal/infrastructure/repos/mysqlreposimpl"
	"example/internal/infrastructure/repos/redisrepoimpl"
	"example/internal/pkg/db"
	"example/internal/pkg/logger"
)

// Injectors from wire.go:

// NewUserAPI 实例化用户控制器
func NewUserAPI(dc *db.Connector, rdb *db.Redis, lg *logger.Logger) *UserHandler {
	userRepository := mysqlreposimpl.NewUserRepository(dc, rdb, lg)
	userService := service.NewUserService(userRepository)
	sessionRepository := redisrepoimpl.NewSessionRepository(rdb)
	sessionService := service.NewSessionService(sessionRepository)
	userHandler := NewUserHandler(userService, sessionService)
	return userHandler
}

// NewAccountAPI 实例化管理员账户控制器
func NewAccountAPI(dc *db.Connector, rdb *db.Redis, lg *logger.Logger) *AccountHandler {
	accountRepository := mysqlreposimpl.NewAccountRepository(dc, rdb, lg)
	accountService := service.NewAccountService(accountRepository)
	sessionRepository := redisrepoimpl.NewSessionRepository(rdb)
	sessionService := service.NewSessionService(sessionRepository)
	accountHandler := NewAccountHandler(accountService, sessionService)
	return accountHandler
}
