// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package handlers

import (
	"example/internal/app/service"
	"example/internal/infrastructure/depend"
	"example/internal/infrastructure/repos/mysqlreposimpl"
	"example/internal/infrastructure/repos/redisrepoimpl"
)

// Injectors from wire.go:

// NewUserAPI 实例化用户控制器
func NewUserAPI(inject *depend.Injecter) *UserHandler {
	userRepository := mysqlreposimpl.NewUserRepository(inject)
	userService := service.NewUserService(userRepository)
	sessionRepository := redisrepoimpl.NewSessionRepository(inject)
	sessionService := service.NewSessionService(sessionRepository)
	userHandler := NewUserHandler(userService, sessionService)
	return userHandler
}

// NewAccountAPI 实例化管理员账户控制器
func NewAccountAPI(inject *depend.Injecter) *AccountHandler {
	accountRepository := mysqlreposimpl.NewAccountRepository(inject)
	accountService := service.NewAccountService(accountRepository)
	sessionRepository := redisrepoimpl.NewSessionRepository(inject)
	sessionService := service.NewSessionService(sessionRepository)
	accountHandler := NewAccountHandler(accountService, sessionService)
	return accountHandler
}
