// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package middlewares

import (
	"example/internal/app/service"
	"example/internal/infrastructure/depend"
	"example/internal/infrastructure/repos/mysqlreposimpl"
	"example/internal/infrastructure/repos/redisrepoimpl"
	"net/http"
)

// Injectors from wire.go:

// NewHandleAuthVerify 创建
func NewHandleAuthVerify(inject *depend.Injecter) func(handler http.Handler) http.Handler {
	sessionRepository := redisrepoimpl.NewSessionRepository(inject)
	sessionService := service.NewSessionService(sessionRepository)
	v := HandleAuthVerify(sessionService)
	return v
}

// NewHandlePermissionVerify
func NewHandlePermissionVerify(inject *depend.Injecter) func(handler http.Handler) http.Handler {
	accountRepository := mysqlreposimpl.NewAccountRepository(inject)
	permissionService := service.NewPermissionService(accountRepository)
	v := HandlePermissionVerify(permissionService)
	return v
}
