// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package middlewares

import (
	"demo/internal/app/service"
	"demo/internal/infrastructure/repos/redis_repos_impl"
	"demo/internal/pkg/db"
	"net/http"
)

// Injectors from wire.go:

// NewHandleAuthVerify 创建
func NewHandleAuthVerify(dc *db.Connector, rdb *db.Redis) func(handler http.Handler) http.Handler {
	sessionRepository := redis_repos_impl.NewSessionRepository(rdb)
	sessionService := service.NewSessionService(sessionRepository)
	v := HandleAuthVerify(sessionService)
	return v
}
