// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package middlewares

import (
	"example/internal/app/service"
	"example/internal/infrastructure/repos/mysqlreposimpl"
	"example/internal/infrastructure/repos/redisrepoimpl"
	"example/internal/pkg/db"
	"example/internal/pkg/logger"
	"net/http"
)

// Injectors from wire.go:

// NewHandleAuthVerify 创建
func NewHandleAuthVerify(dc *db.Connector, rdb *db.Redis) func(handler http.Handler) http.Handler {
	sessionRepository := redisrepoimpl.NewSessionRepository(rdb)
	sessionService := service.NewSessionService(sessionRepository)
	v := HandleAuthVerify(sessionService)
	return v
}

// NewHandlePermissionVerify
func NewHandlePermissionVerify(dc *db.Connector, rdb *db.Redis, lg *logger.Logger) func(handler http.Handler) http.Handler {
	accountRepository := mysqlreposimpl.NewAccountRepository(dc, rdb, lg)
	permissionService := service.NewPermissionService(accountRepository)
	v := HandlePermissionVerify(permissionService)
	return v
}
